apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "lexi-shift" 
  namespace: "default"
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  predictor:
    containers:
      - name: translation-service
        image: ghcr.io/bnallapeta/lexi-shift:0.0.1
        env:
        - name: MODEL_SIZE
          value: "small"
        - name: MODEL_DEVICE
          value: "cpu"
        - name: MODEL_COMPUTE_TYPE
          value: "float32"
        - name: SERVER_LOG_LEVEL
          value: "info"
        ports:
        - name: http1
          containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /ready
            port: http1
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http1
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: model-cache
          mountPath: /tmp/nllb_models
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
    volumes:
    - name: model-cache
      emptyDir: {}
    imagePullSecrets:
    - name: acr-secret
